# coding: utf-8

"""
    balenahal

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import balenahal
from balenahal.api.leds_api import LedsApi  # noqa: E501
from balenahal.rest import ApiException


class TestLedsApi(unittest.TestCase):
    """LedsApi unit test stubs"""

    def setUp(self):
        self.api = balenahal.api.leds_api.LedsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_off(self):
        """Test case for off

        """
        pass

    def test_on(self):
        """Test case for on

        """
        pass


if __name__ == '__main__':
    unittest.main()
